import { Router } from "express";
import usersRouter from './users.js';
import analyseRouter from './analyse.js';
import chatbotRouter from './chatbot.js';
import historyRouter from './history.js';
import predictionRouter from './prediction.js';
import exportRouter from './export.js';
import notificationsRouter from './notifications.js';
const router = Router();
router.use(usersRouter);
router.use(analyseRouter);
router.use('/api/chatbot', chatbotRouter);
router.use('/api/history', historyRouter);
router.use(predictionRouter);
router.use('/api/export', exportRouter);
router.use('/api', notificationsRouter);
export default router;